<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit0eb3a46238584c371cb6d97660d612e7
{
    public static $prefixLengthsPsr4 = array (
        'm' => 
        array (
            'magicTrucks\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'magicTrucks\\' => 
        array (
            0 => __DIR__ . '/../..' . '/class',
        ),
    );

    public static $classMap = array (
        'AltoRouter' => __DIR__ . '/..' . '/altorouter/altorouter/AltoRouter.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit0eb3a46238584c371cb6d97660d612e7::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit0eb3a46238584c371cb6d97660d612e7::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit0eb3a46238584c371cb6d97660d612e7::$classMap;

        }, null, ClassLoader::class);
    }
}
